name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: windows-latest
    steps:    
    - uses: actions/checkout@v2     
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x86'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linters.txt
    - name: Lint with isort
      run: python -m isort . --check-only --diff
    - uses: psf/black@stable
      with:
        args: ". --check"
    - name: Lint with flake8
      run: python -m flake8 .
    - name: Lint with mypy
      run: python -m mypy .
  build:
    runs-on: ubuntu-latest
    env: 
      FILES: "*.py LICENSE license/ vendor/"
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Package as tar
      run: tar czf ${{ github.event.repository.name }}.tar.gz $FILES
    - name: Package as zip
      run: zip ${{ github.event.repository.name }}.zip $FILES

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            ${{ github.event.repository.name }}.tar.gz
            ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



