name: CI

on: [push, pull_request]

env:
  MOD_NAME: Eridium

jobs:
  check:
    runs-on: windows-latest
    # defaults:
    #   run:
    #     working-directory: PythonSDK/Mods/${{ env.MOD_NAME }}
    steps:
    - run: echo "$MOD_NAME"
    - run: pwd
      working-directory: PythonSDK/Mods/${{ env.MOD_NAME }}

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x86'

    - name: Clone PythonSDK Mods
      run: |
        git clone --depth 1 --filter=blob:none --sparse https://github.com/bl-sdk/PythonSDK
        cd PythonSDK
        git sparse-checkout init --cone
        git sparse-checkout set Mods
    - uses: actions/checkout@v2     
      with:
        path: PythonSDK/Mods/${{ env.MOD_NAME }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linters.txt
    - name: Lint with isort
      run: python -m isort . --check-only --diff
    - name: Lint with black
      run: python -m black . --check
    - name: Lint with flake8
      run: python -m flake8 . -v --show-source --statistics
    - name: Lint with mypy
      run: python -m mypy . -v --pretty
  build:
    runs-on: ubuntu-latest
    env: 
      FILES: "*.py LICENSE license/ vendor/"
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Package as tar
      run: tar czf ${{ github.event.repository.name }}.tar.gz $FILES
    - name: Package as zip
      run: zip ${{ github.event.repository.name }}.zip $FILES

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            ${{ github.event.repository.name }}.tar.gz
            ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



